### ISSUE TITLE
HotDistance

### ISSUE THREAD

**Issue by mzouink** [janelia-cellmap/dacapo#10]

**Comment by rhoadesScholar** [comment]
@mzouink It seems like maybe we should set it up so that Tasks are composable (e.g. HotDistance = OneHot + Distance) from within DaCapo?

**Comment by mzouink** [comment]
Exactly, we did that one already but need to be finished, tested and merged.

+ we can start we new task - InnerDistanceTask = Distance * binary
So no more masks. related to https://github.com/janelia-cellmap/dacapo/issues/28
