### ISSUE TITLE
Add Security-Bot

### ISSUE THREAD

**Issue by rhoadesScholar** [janelia-cellmap/dacapo#102]
There are entry points for code injection. Code in repo needs to be checked to not be malicious.

**Comment by rhoadesScholar** [comment]
See https://github.com/janelia-cellmap/dacapo/settings/security_analysis

**Comment by cmalinmayor** [comment]
We looked into this and we have dependabot check dependencies for vulnerabilities and open patch PRs. We also have github code scanning detect vulnerabilities in our code. It would be hard to check user supplied functions for maliciousness - probably not within scope at this time.
