### ISSUE TITLE
Make `predict` consistent between internal and CLI dacapo

### ISSUE THREAD

**Issue by adjavon** [janelia-cellmap/dacapo#115]
At the moment from 6820aa8 there is an inconsistency with the function signature of `dacapo.predict` which causes `validate` and `apply` (and tests) to fail. 

The fix that I am currently considering looks a lot like 48de078 where `dacapo.cli.predict` is loading configurations from files and then calls `dacapo.predict` with the original function signature.

**Comment by adjavon** [comment]
@rhoadesScholar do you remember why you changed both to the `cli` signature?

**Comment by rhoadesScholar** [comment]
should be good to go now.
