### ISSUE TITLE
Funkelab.persistence dependency

### ISSUE THREAD

**Issue by mzouink** [janelia-cellmap/dacapo#17]
Using funkelab.persistence is adding a new level of depency that should be maintained by us.
One of the things we want to do in the hackathon is skip using funkelab.persistence. 
Currently we only using Arrays and datasets (prepare_ds, open_ds): https://github.com/funkelab/funlib.persistence/tree/main/funlib/persistence/arrays 
it is used in DaCapo and ML_experiments.
@d-v-b 
It will be very nice if you can check this two files and see if we can delete them and using xarray directly. or we keep them and we build them in top of xarray instead

Problems: 
- Maintainabily
- Doesn't support ome_zarr

**Comment by d-v-b** [comment]
[This class](https://github.com/funkelab/funlib.persistence/blob/7381b3b22e06aa17a4a869a758f959046e89ed7f/funlib/persistence/arrays/array.py#L6) could certainly be instantiated from an `xarray.DataArray`. I suspect the majority of the methods of this class could also be implemented as either methods of a subclass of `xarray.DataArray`, or as plain old functions

**Comment by d-v-b** [comment]
and [this function](https://github.com/funkelab/funlib.persistence/blob/7381b3b22e06aa17a4a869a758f959046e89ed7f/funlib/persistence/arrays/datasets.py#L17) could be made to handle ome-ngff 0.4 spatial metadata without a huge amount of effort

**Comment by d-v-b** [comment]
but it's not possible to answer your question without seeing how your code is calling the methods defined on the classes you want to remove
