### ISSUE TITLE
Incorporate insights from Cellpose/Carsen

### ISSUE THREAD

**Issue by rhoadesScholar** [janelia-cellmap/dacapo#28]
**On distance masking:**

- Make distance mask for whole crop (save alongside)
- Precompute targets?
- Without distance outside object, no distance mask is needed

**Sparse data:**
- Consider using targets:
  - boundary pixels (BCE)
  - flows (MSE)
  - probability (BCE)
  - center prediction

**Loss weighting:**
- Sample crops based on organelles
  - Balance sampling instead of balancing loss weights
  - _Changing loss weights changes gradient magnitudes constantly which is difficult for Adam optimizer_

BCE for binary class predictions --> MSE doesn’t penalize false positives
  - Weight BCE compared to MSE

(Center of object (for flow calculation) is calculated as object-pixel rounded center of mass)
Try 4 convolutions per block in UNet (2x2 —> see CellPose 3)

**Comment by davidackerman** [comment]
include Cellpose Unet for #9
