### ISSUE TITLE
Finish Apply.py

### ISSUE THREAD

**Issue by mzouink** [janelia-cellmap/dacapo#44]
Then don't forget to remove the exclude from mypy

**Comment by mzouink** [comment]
i did remove them from main for now

**Comment by rhoadesScholar** [comment]
Branch ready to incorporate with blockwise dev.

Note: get_overall_best() still needs to be implemented for apply to be complete.

**Comment by rhoadesScholar** [comment]
Merged into [56-[a](https://github.com/janelia-cellmap/dacapo/tree/57-parallel-blockwise-processing)
